version: '2'
services:
    protractor-app:
        image: protractor
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://protractor-mysql:3306/protractor?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    protractor-mysql:
        extends:
            file: mysql.yml
            service: protractor-mysql
